name: android
on:
  workflow_dispatch:
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with: 
          submodules: 'recursive'
      - name: build
        run: |
          cd android/android_studio_project/app
          ./gradlew assembleDebug -Dorg.gradle.java.home=/usr/lib/jvm/temurin-18-jdk-amd64
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: xenia-app.apk
          path: android/android_studio_project/app/build/outputs/apk/debug/*.apk
